### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [Sarunas-cpu/FileStorage#1]
When trying to compile a fresh clone, I get this error:

![image](https://user-images.githubusercontent.com/21359162/153859696-f97fdd3b-22cd-4094-9713-2299ffb05e2b.png)

Looks like one of the paths is hardcoded? `C:\Users\serio\source\repos\SyncTask\...`

**Comment by Sarunas-cpu** [comment]
Strange. Just tried to clone using Visual Studio 2019 on a different machine and I do not seem to get any errors while compiling. Have you tried cleaning the solution and rebuilding it?

Sent from Mail for Windows

From: Edvardas Dlugauskas
Sent: 14 February 2022 14:49
To: Sarunas-cpu/FileStorage
Cc: Subscribed
Subject: [Sarunas-cpu/FileStorage] Fails to compile (Issue #1)

When trying to compile a fresh clone, I get this error:

Looks like one of the paths is hardcoded? C:\Users\serio\source\repos\SyncTask\...
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EdvardasDlugauskas** [comment]
Worked for me on a different machine, I'll try again tomorrow
